/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32_f103c6_EXTI_driver.h>
#include <stm32_f103c6_gpio_driver.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

GPIO_CONFIGURATION GPIO_cnfg;

void hal_init();
void StartOS(void);


int main(void)
{

	hal_init();
	StartOS();


    /* Loop forever */
	for(;;);
}

void hal_init()
{
	RCC_GPIOA_CLOCK_ENABLE;

	GPIO_cnfg.GPIO_OUTPUT_SPEED =GPIO_OUTPUT_10MHz;
	GPIO_cnfg.GPIO_PIN_MODE = GPIO_PUSHPULL_OUTPUT;
	GPIO_cnfg.GPIO_PIN_NUMBER =GPIO_PIN7;
	MCAL_GPIO_INIT(GPIOA, &GPIO_cnfg);

	GPIO_cnfg.GPIO_PIN_MODE = GPIO_FLOATING_INPUT;
	GPIO_cnfg.GPIO_PIN_NUMBER =GPIO_PIN3;
	MCAL_GPIO_INIT(GPIOA, &GPIO_cnfg);







}


#define CYCLES_PER_LOOP 3
void wait_cycles( uint32_t n ) {
	uint32_t l = n/CYCLES_PER_LOOP;
	asm volatile( "0:" "SUBS %[count], 1;" "BNE 0b;" :[count]"+r"(l) );
}

void StartOS(void){
	uint8_t i = 0;
	while(1){
		if(i==10){
			ReadDoorSensor_Runnable();
			i++;
		}
		else if(i==12){
			DoorLock_indication_runnable();
			i=0;
		}
		else{
			i++;
		}
		wait_cycles(10);
	}
}

